---
title: "LSL-unemployment"
author: "Tara Jagadeesh"
date: "10/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Limitations: 




```{r}
#Load packages
library(tidyverse) #Data wrangling
library(sf) #Shapefiles
library(here) #Loading data
library(rgdal)
library(stringr)

```

```{r}
############################# Data Wrangling ############################# 

#Load data for LSL inventory
SL <- read_csv("ServiceLineMaterialInventoryReports.csv")

LSL_county <- SL %>% 
  filter(ReportingYear == "2018") %>%  #Keep only year 2018
  group_by(County) %>% #Summarize data with county totals
  summarize(TotalServiceConnections = sum(TotalServiceConnections), 
            ServicesLead = sum(ServicesLead),
            ServicesUnknownMaterial = sum(ServicesUnknownMaterial)) %>% 
  mutate(potential = ServicesLead + ServicesUnknownMaterial, #Add column for potential LSLs
         invest = potential*8000, # $$ to be invested (at a rate of $8000 per line)
         output_econ = invest*1.64, #Economic output using Quinn et al. (2014) figure
         output_jobs_total = invest/1000000*16, #Jobs output using Quinn et al. (2014) figure
         output_jobs_yearly = output_jobs_total/20 ) #Divided over 20 years
  

#Load data for unemployment rate in Illinois by county 
unemployment_raw<-read_csv(here("Map-Data","Unemployment","laucntycur14.csv"))

# Wrangle data into useable format
names(unemployment_raw) <- unemployment_raw[4,] #Reassign header row
unemployment_raw <- unemployment_raw[-c(1:5),] #Remove excess rows

colnames(unemployment_raw) <- make.unique(names(unemployment_raw)) #Give each column a unique name

unemployment_county <- unemployment_raw %>% 
  separate(., `County Name/State Abbreviation`, c("County","State"), sep = ", ") %>% #Separate County and State
  separate(., County, c("County","x"), sep = " County") %>% #Remove the word "County" to match LSL data
  separate(., County, c("County","x"), sep = " County") %>% 
  select(-x) %>% 
  rename(LAUS_code = "LAUS Code", #Rename columns
         FIPS_State = Code,
         FIPS_County = Code.1,
         State = State,
         LaborForce = Force,
         UR = "(%)") %>% 
  mutate(LaborForce = as.numeric(gsub(",", "", LaborForce)), #Convert to numeric without commas
         Employed = as.numeric(gsub(",", "", Employed)),
         Unemployed = as.numeric(gsub(",", "", Unemployed)),
         UR = as.numeric(UR)) %>% 
  filter(State == "IL", #Keep only data for IL 
         Period == "Aug-20") 

#Join LSL and unemployment data
LSL_unemployment <- merge(LSL_county, unemployment_county, by = "County") %>% 
  select(-LAUS_code, -FIPS_State, -State, -Period, UR) %>% 
  mutate(UR = Unemployed/LaborForce*100,
         perc_potentialEmployed = output_jobs_yearly/Unemployed*100,
         new_Unemployed = Unemployed - output_jobs_yearly,
         new_UR = new_Unemployed/LaborForce*100,
         change_UR = new_UR-UR)

```


```{r}
############################# Stats ############################# 

#Potential Employment (% of unemployed that could be employed)
  # Overall
    #Total number of people unemployed 
    sum(LSL_unemployment$Unemployed) #699,268 people
    
    #Total number of potential jobs
    sum(LSL_unemployment$output_jobs_yearly) #11222.55 jobs
    
    #Total percent of potential employment?
    sum(LSL_unemployment$output_jobs_yearly)/sum(LSL_unemployment$Unemployed)*100 #1.6%
    
    #Total $$$ invested
    sum(LSL_unemployment$invest) # $14,028,184,000
  
  # By County 
    #Histogram
    hist(LSL_unemployment$perc_potentialEmployed)
    
    #Mean percent of potential employment
    mean(LSL_unemployment$perc_potentialEmployed) #2.381589
    
    #Median percent of potential employment
    median(LSL_unemployment$perc_potentialEmployed) #1.91619

#Potential Change in UR 
  # Overall
    #UR
    UR <- sum(LSL_unemployment$Unemployed)/sum(LSL_unemployment$LaborForce)*100 #11.06469
    
    #New UR 
    new_UR <- sum(LSL_unemployment$new_Unemployed)/sum(LSL_unemployment$LaborForce)*100 #10.88711
    
    #Overall change in UR
    new_UR-UR #-0.1775771
    
    # Investing in LSL replacement could decrease the unemployment rate in IL by 0.18%
    
  # By County 
    #Histogram
    hist(LSL_unemployment$change_UR)
    
    #Mean percent of potential change in UR
    mean(LSL_unemployment$change_UR) #-0.1848287
    
    #Median percent of potential change in UR
    median(LSL_unemployment$change_UR) #-0.1614763
    
    # Investing in LSL replacement could decrease the unemployment rate in IL counties by an average of 0.18%
```








```{r}
############################# Mapping ############################# 
#Load county data


  

```

```{r}

############################# LSL Statistics ############################# 

#Total # of LSLs
  #Total service lines
  sum(LSL$TotalServiceConnections) #3,842,374

  #Known lead
  sum(LSL$ServicesLead) #686,259
  sum(LSL$ServicesLead)/sum(LSL$TotalServiceConnections)*100 #17.9%
  sum(LSL$ServicesLead)
  
  #Unknown lines
  sum(LSL$ServicesUnknownMaterial) #1,067,649
  sum(LSL$ServicesUnknownMaterial)/sum(LSL$TotalServiceConnections)*100 #27.8%
  
  #Potentially lead
  sum(LSL$ServicesLead + LSL$ServicesUnknownMaterial) #1,753,908
  sum(LSL$ServicesLead + LSL$ServicesUnknownMaterial)/sum(LSL$TotalServiceConnections)*100 #45.6%
  
#Total # of residents
  sum(unemployment$total_pop)

#% of state population 
  

```

# Analysis 1 - Correlation between unemployment and LSL
```{r}
############################# Correlations (Known LSLs)  ############################# 

######### Labor Force Participation ######### 

  ggplot(LSL_unemployment_filter, aes(x = LFPR, y = perc_lead)) +
    geom_point()+
    geom_smooth(method=lm)+
    labs(title="",
       x ="Labor Force Participation Rate (%)", y = "Municipal Service Lines Made of Lead (%)")

  lm_LFPR_percLSL_K <- lm(LFPR ~ perc_lead, data = LSL_unemployment_filter)
  summary(lm_LFPR_percLSL_K)

  
######### Employment/Population ######### 

  ggplot(LSL_unemployment_filter, aes(x = EPR, y = perc_lead)) +
    geom_point()+
    geom_smooth(method=lm)+
    labs(title="",
       x ="Employment/Population Rate (%)", y = "Municipal Service Lines Made of Lead (%)")

  lm_EPR_percLSL_K <- lm(EPR ~ perc_lead, data = LSL_unemployment_filter)
  summary(lm_EPR_percLSL_K)

######### Unemployment Rate ######### 

  ggplot(LSL_unemployment_filter, aes(x = UR, y = perc_lead)) +
    geom_point()+
    geom_smooth(method=lm)+
    labs(title="",
       x ="Unemployment Rate (%)", y = "Municipal Service Lines Made of Lead (%)")

  lm_UR_percLSL_K <- lm(UR ~ perc_lead, data = LSL_unemployment_filter)
  summary(lm_UR_percLSL_K)
  

  


```
End here
